# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transctrl_pb2 as transctrl__pb2


class TransmissionControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reconcile = channel.unary_unary(
                '/transctrl.TransmissionController/Reconcile',
                request_serializer=transctrl__pb2.DesiredState.SerializeToString,
                response_deserializer=transctrl__pb2.ReconcileResult.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/transctrl.TransmissionController/GetStatus',
                request_serializer=transctrl__pb2.Empty.SerializeToString,
                response_deserializer=transctrl__pb2.CurrentState.FromString,
                )
        self.GetInstance = channel.unary_unary(
                '/transctrl.TransmissionController/GetInstance',
                request_serializer=transctrl__pb2.InstanceId.SerializeToString,
                response_deserializer=transctrl__pb2.InstanceStatus.FromString,
                )


class TransmissionControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Reconcile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransmissionControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reconcile': grpc.unary_unary_rpc_method_handler(
                    servicer.Reconcile,
                    request_deserializer=transctrl__pb2.DesiredState.FromString,
                    response_serializer=transctrl__pb2.ReconcileResult.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=transctrl__pb2.Empty.FromString,
                    response_serializer=transctrl__pb2.CurrentState.SerializeToString,
            ),
            'GetInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstance,
                    request_deserializer=transctrl__pb2.InstanceId.FromString,
                    response_serializer=transctrl__pb2.InstanceStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transctrl.TransmissionController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransmissionController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reconcile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transctrl.TransmissionController/Reconcile',
            transctrl__pb2.DesiredState.SerializeToString,
            transctrl__pb2.ReconcileResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transctrl.TransmissionController/GetStatus',
            transctrl__pb2.Empty.SerializeToString,
            transctrl__pb2.CurrentState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transctrl.TransmissionController/GetInstance',
            transctrl__pb2.InstanceId.SerializeToString,
            transctrl__pb2.InstanceStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
